require 'rubygems'
require 'sequel-reporter'

task :environment do
  Sequel::Reporter::Config.instance.load_user_config(File.dirname(__FILE__))
  Sequel::Reporter::Database.connect
end

namespace :db do
  task :migrate => :environment do
    Sequel::Reporter::Database.run_migrations
  end
end
